project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from soc.views import index, table, departments, dept_info, download, search


urlpatterns = [
    url(r'^accounts/', include('djangosaml2.urls')),
    url(r'^$', index),
    url(r'^dept_id', dept_info),
    url(r'^table/', table),
    url(r'^search/', search),
    url(r'^download/', download),
    url(r'^dept_grps/$', departments),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ht/$', include('health_check.urls')),
]

if settings.DEBUG:
  import debug_toolbar
  urlpatterns = [
    url(r'^debug/', include(debug_toolbar.urls)),
  ] + urlpatterns

soc/forms.py
from django import forms
from models import um_ecomm_dept_units_rept, Search
from django.utils.dates import MONTHS

class MainForm(forms.Form):

  dept_id_range = forms.CharField(label='Department IDs', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'type individual ids or a range of ids'}), required=False)

  DEPT_GRPS = list(um_ecomm_dept_units_rept.objects.order_by().values_list('dept_grp', flat=True).distinct())

  DEPT_GRP_BUD_SEQ = list(um_ecomm_dept_units_rept.objects.order_by().values_list('dept_bud_seq', flat=True).distinct())

  DEPT_GRP_VP  = list(um_ecomm_dept_units_rept.objects.order_by().values_list('dept_grp_vp_area', flat=True).distinct())

  dept_grp_vp_choice = forms.ChoiceField(required=False, choices=((x, x.replace('_', ' ').lower()) for x in DEPT_GRP_VP))
  dept_grp_bud_choice = forms.ChoiceField(required=False, choices=((x, x.replace('_', ' ').lower()) for x in DEPT_GRP_BUD_SEQ))
  dept_grp_choice = forms.ChoiceField(required=False, choices=((x, x.replace('_', ' ').lower()) for x in DEPT_GRPS))

  fiscal_yr = forms.ChoiceField(required=False, choices=((str(x), x) for x in range(2017,2005, -1)))
  calendar_yr = forms.ChoiceField(required=False, choices=((str(x), x) for x in range(2017,2005, -1)))


  range_begin_m = forms.ChoiceField(choices=MONTHS.items())
  range_begin_y = forms.ChoiceField(choices=((str(x), x) for x in range(2017,2008, -1)))
  
  range_end_m = forms.ChoiceField(choices=MONTHS.items())
  range_end_y = forms.ChoiceField(choices=((str(x), x) for x in range(2017,2008, -1)))

  t_choice = forms.CharField(max_length=1)

  def save(self, dept, time):
    search = Search(dept=dept, time=time)
    search.save()

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Summary Of Charges ITS</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

        <script src="{% static 'js/float.js' %}"></script>

        <script src="https://use.fontawesome.com/0558958f06.js"></script>

        <link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        {% block index %}
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load widget_tweaks %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block index %}
<nav class="navbar fixed-top navbar-light bg-faded">
    <a class="navbar-brand" href="/">
        <img src="{% static 'img/head.png' %}" height="30" class="d-inline-block align-top" alt="">
    </a>
</nav>
<div class="container card top-row">
    <div class="pb-3 ">
        <form id="main-form" class="pt-3" action="/table/" method="POST">{% csrf_token %}

            <input type="hidden" name="t_choice" id="t_choice_id" value="" />
            <input type="hidden" name="dept_id_range" id="dept_id_range_actual" value="" />

            <input type="hidden" name="fiscal_yr" id="f_yr_in" value="" />
            <input type="hidden" name="calendar_yr" id="c_yr_in" value="" />

            <div class="row index-top pb-4">
                <div class="col-md-6 col-xs-12 pl-3 col-md-border d-flex" style="flex-direction: column;">
                    <h3>Department Look Up</h3>
                    <div class="d-flex mb-3">
                        <input class="form-control" id="tree-input" aria-describedby="emailHelp" placeholder="Search by department">
                        <button class="btn blue" type="button" id="tree-search-btn">
                            <div id="search-text">Search</div>
                            <div id="load-spinner">
                            </div>
                        </button>
                    </div>
                    <div id="tree-div" class="tree-div">
                        {% include "tree.html" %}
                    </div>
                    <div class="d-flex pt-2 pl-2">
                        <p class="text-muted"><small>
                            Add departments and/or department groups to the table for making the report by clicking on the (+) icon next to their name.
                        </small></p>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12 col-md-border">
                    <h3> Department IDs</h3>
                    <div class="d-flex">
                        {{ form.non_field_errors }}
                        {{ form.dept_id_range.errors }}
                        <input type="text" id="id_dept_id_range" placeholder="type individual ids or a range of ids" class="form-control" maxlength="20">
                        <button class="btn blue" type="button" id="submit-dept-btn"> + </button>
                    </div>
                    <div class="d-flex">
                        <div id="alert" class="alert alert-danger hidden w-100 my-2" role="alert">
                            <strong>Error</strong> Department not found.
                        </div>
                    </div>
                    <div class="left-col">
                        <table class="table table-bordered mt-3">
                            <thead class="blue">
                                <tr>
                                    <th style="width: 30%">Department ID</th>
                                    <th>Department Name</th>
                                </tr>
                            </thead>
                            <tbody id="dept_ids_table">
                            </tbody>
                        </table>
                        <div class="d-flex">
                            <small class="text-muted">Remove departments and/or department groups from the table(and the report) by clicking on the (-) icon next to their name.
                            </small>
                        </div>
                    </div>
                    <h3 class="pt-5"> Date Range </h3>
                    <div class="d-flex align-items-center pl-3">
                        <label class="custom-control custom-radio pl-3">
                            <input id="whole-year" name="date_radio" type="radio" class="custom-control-input" checked>
                            <span class="custom-control-indicator"></span>

                        </label>
                        <div class="bold" id="fy-tag">
                            Fiscal Year
                        </div>

                        <label class="switch">
                            <input name="fc_choice" type="checkbox">
                            <span style="background-color: #9c9898;" id="date-slide" class="slider round"></span>
                        </label>
                        <div id="c-tag">
                            Calendar Year
                        </div>
                        <select id="year" class="select form-control-sm ml-3">
                            <option value="2016">2016</option>
                            <option value="2015">2015</option>
                            <option value="2014">2014</option>
                            <option value="2013">2013</option>
                            <option value="2012">2012</option>
                            <option value="2011">2011</option>
                            <option value="2010">2010</option>
                            <option value="2009">2009</option>
                            <option value="2008">2008</option>
                            <option value="2007">2007</option>
                            <option value="2006">2006</option>
                            <option value="2005">2005</option>
                        </select>
                    </div>
                    <div class="d-flex pl-5 pt-2">
                        <small class="text-muted ">eg. Fiscal Year 2016 = July 2015 - June 2016</small>
                    </div>
                    <div class="d-flex pl-5">
                        <small class="text-muted ">eg. Calendar Year 2016 = January 2016 - December 2016</small>
                    </div>
                    <hr>
                    <div class="pl-3">
                        <div class="d-flex flex-row">
                            <label class="custom-control custom-radio pl-3">
                                <input id="d_grp_vp" name="date_radio" type="radio" class="custom-control-input">
                                <span class="custom-control-indicator"></span>
                            </label>
                            <div>
                                Enter date range
                            </div>
                        </div>
                        <div class="d-flex flex-row pl-4">
                            <div class="p-2">
                                {{ form.range_begin_m| add_class:"select form-control-sm"}}
                            </div>
                            <div class="p-2">
                                {{ form.range_begin_y| add_class:"select form-control-sm"}}
                            </div>
                            <div class="p-2">
                                TO
                            </div>
                            <div class="p-2">
                                {{ form.range_end_m| add_class:"select form-control-sm"}}
                            </div>
                            <div class="p-2">
                                {{ form.range_end_y| add_class:"select form-control-sm"}}
                            </div>
                        </div>

                    </div>
                    <div class="d-flex pl-5 pt-2">
                        <small class="text-muted ">For a single month, make the following selection - March 2016 = March 2016 TO March 2016</small>
                    </div>
                    <hr>
                    <div class="d-flex pl-3">
                        <input class="btn blue" style="width:100%;" type="submit" value="Generate Report">

                    </div>
                </div>
            </div>

        </form>
    </div>
</div>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/secret.html
{% extends 'base.html' %}
{% block index %}
<p>{{key}}</p>
{% endblock %}

templates/table.html
{% extends 'base.html' %}
{% load humanize %}
{% load money_format %}
{% load staticfiles %}
{% block index %}
<nav class="navbar fixed-top navbar-light bg-faded">
    <div class="row ">
        <div class="col-md-6">
            <h4>{{unit}}</h4>
        </div>
        <div class="col-md-6">
            <h4>{{dateRange}}</h4>
        </div>
    </div>
    <div class="d-flex justify-content-end align-items-center">
        <div class="p-2">
            Expand All
        </div>

        <label class="switch mx-0" style="margin-bottom: .25rem;">
            <input name="ex_choice" type="checkbox">
            <span style="background-color: #9c9898;" id="expand-slide" class="slider round"></span>
        </label>

        <div class="p-2">
            Hide All
        </div>
        <div class="p-2">
            <button class="btn btn-sm float-right t-total" id="download-btn"onclick="location.href = '/download';">  Download .xls </button>
        </div>
    </div>
    <div class="row">
        <div style="padding-left: 1.5rem; width: 25%;">Account</div>
        <div style="padding: .3rem; width: 42%;">Description</div>
        <div style="padding: .3rem; width: 7%;">Rate</div>
        <div style="padding: .3rem; width: 8%;">Avg monthly Billed</div>
        <div style="padding: .3rem; width: 9%;">Billed Units</div>
        <div style="padding: .3rem; width: 9%;">Total</div>
    </div>
</nav>
<div class="container-fluid top">
    <table id="main-table" class="table table-sm table-hover">
        <tbody>
            <!-- for each account -->
            {% for account in accounts %}
            <tr class="account-row">
                <td>
                    <strong>{{forloop.counter | roman }}</strong>
                    <i id="group-{{forloop.counter}}-drop" class="fa fa-minus-circle" aria-hidden="true"></i>

                    <strong>{{account.desc}}  ({{account.num}})</strong>
                </td>
                <td colspan="4"></td>
                <td class="account-total">
                    <!-- account total -->
                    {{account.total|floatformat:2|money}}
                </td>
            </tr>

            <!--for each group -->
            {% for group in account.items %}
            <tr id="item-{{forloop.parentloop.counter}}">

                <td>
                    {{forloop.counter}}.
                    <i id="item-{{forloop.parentloop.counter}}-{{forloop.counter}}-drop" class="fa fa-plus-circle" aria-hidden="true"></i>
                    {{group.grp}}
                </td>
                <td colspan="4"></td>
                <td class="cat-total">
                    <!-- group total -->
                    {{group.total|floatformat:2|money}}
                </td>
            </tr>
            <!-- for each item in group -->
            {% for item in group.items %}
            <tr id="item-{{forloop.parentloop.parentloop.counter}}-{{forloop.parentloop.counter}}" class="item-row hidden">
                <td></td>
                <td >{{item.descr}}<strong> - {{item.cc|default_if_none:""}}</strong></td>
                <td>{{item.unit_rate|floatformat:2|money}}</td>
                <td class="hidden-md-down">{{item.monthly}}</td>
                <td class="hidden-lg-up"</td>
                <td>{{item.quantity|default_if_none:""|floatformat:0}}</td>
                <td>{{item.total|floatformat:2|money}}</td>
            </tr>
            {% endfor %}
            <!-- endfor items-->

            {% endfor %}
            <!-- endfor group -->


            {% empty %}
            <div class="row">
                <h4 class="text-danger"> No records found </h4>
                <a class=""href="/">Go Back</a>
            </div>
            {% endfor %}
            <!-- endfor account -->
            <tr>
                <td> <strong>Total ITCom Charges</strong></td>
                <td colspan="4"></td>
                <td class="t-total">
                    ${{total|floatformat:2|intcomma}}
                </td>
            </tr>
    </table>
</div>

<!-- debug table
    <table class="table table-bordered table-responsive">
    <thead class="thead">
    <tr>
    <th>Expense Account</th>
    <th>Item Description & code</th>
    <th>Rate</th>
    <th>Avg Monthly Units Billed</th>
    <th>Billed Units</th>
    <th>Item Total</th>
    <th>Item Group Total</th>
    <th>Account Total</th>
    </tr>
    </thead>
    <tbody>
    {% for acc in accounts %}
    <tr>
    <td>{{acc.num}} - {{acc.total}}</td>
    </tr>

    {% for cg in acc.items %}
    <tr>
    <td>{{cg.grp}} - {{cg.total}}</td>
    </tr>
    <tr>
    {% for d in cg.items %}
    <td>{{d.descr}}</td>
    <td>{{d.total}}</td>
    <td>{{d.m_count}}</td>
    {% endfor %}
    </tr>
    {% endfor %}
    {% endfor %}
    </tbody>
    </table>
-->

<script src="{% static 'js/table.js' %}"></script>
{% endblock %}

templates/tree-dynamic.html
{% for vp in d %}
<div id="vp-{{vp.0}}">
    <p class="bold">
    <i class="fa fa-caret-down mr-2" aria-hidden="true"></i>
    {{vp.1}}
    <i class="fa fa-plus-circle" id="add-vp-{{vp.0}}-{{vp.1}}"></i>
    </p>

    {% for grp in vp.2 %}
    <div id="vp-{{vp.0}}-grp-{{grp.0}}">
        <p class="pl-2">
        <i class="fa fa-caret-down mr-2" aria-hidden="true"></i>
        {{grp.0}} - {{grp.1}}
        <i class="fa fa-plus-circle" id="add-grp-{{grp.0}}-{{grp.1}}"></i>
        </p>
        {% for dept in grp.2 %}
        <div id="vp-{{vp.0}}-grp-{{grp.0}}-dept-{{dept.0}}">
            <small class="pl-4"> {{dept.0}} - {{dept.1}} </small>
            <i class="fa fa-plus-circle" id="add-d-{{dept.0}}-{{dept.1}}"></i>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endfor %}